name: cardbiomedbench-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.13
  - aiosignal=1.3.2
  - annotated-types=0.7.0
  - anthropic=0.49.0
  - anyio=4.8.0
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - cryptography=44.0.2
  - datasets=3.3.2
  - dill=0.3.8
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - filelock=3.17.0
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glog=0.7.1
  - google-ai-generativelanguage=0.6.15
  - google-api-core=2.24.1
  - google-api-python-client=2.162.0
  - google-auth=2.38.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.8.4
  - googleapis-common-protos=1.68.0
  - grpcio=1.67.1
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httplib2=0.22.0
  - httpx=0.28.1
  - huggingface_hub=0.29.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jiter=0.8.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.35.0
  - libgoogle-cloud-storage=2.35.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.6
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - numpy=2.2.3
  - openai=1.65.2
  - openssl=3.4.1
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - pip=25.0.1
  - prometheus-cpp=1.3.0
  - propcache=0.2.1
  - proto-plus=1.26.0
  - protobuf=5.28.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pyopenssl=25.0.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rsa=4.9
  - s2n=1.5.11
  - safetensors=0.5.3
  - setuptools=75.8.2
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - tk=8.6.13
  - tokenizers=0.21.0
  - tqdm=4.67.1
  - transformers=4.49.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - uritemplate=4.1.1
  - urllib3=2.3.0
  - wheel=0.45.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.18.3
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - sympy==1.13.1
      - torch==2.6.0
      - triton==3.2.0