name: cardbiomedbench-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.11.6
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anthropic=0.39.0
  - anyio=4.6.2.post1
  - arrow=1.3.0
  - async-timeout=5.0.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.3
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.1
  - aws-c-io=0.15.2
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.1
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.4
  - aws-sdk-cpp=1.11.449
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - binaryornot=0.4.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.3.0
  - cookiecutter=2.6.0
  - cpython=3.9.20
  - cryptography=43.0.3
  - cycler=0.12.1
  - datasets=3.1.0
  - dill=0.3.8
  - distro=1.9.0
  - evaluate=0.4.1
  - exceptiongroup=1.2.2
  - filelock=3.16.1
  - fonttools=4.55.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-ai-generativelanguage=0.6.10
  - google-api-core=2.22.0
  - google-api-python-client=2.153.0
  - google-auth=2.36.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.8.3
  - googleapis-common-protos=1.66.0
  - grpcio=1.67.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httplib2=0.22.0
  - httpx=0.27.2
  - huggingface_hub=0.26.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - jinja2=3.1.4
  - jiter=0.7.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libparquet=18.0.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.49.2
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.4
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - mdurl=0.1.2
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.2.1
  - numpy=2.0.2
  - openai=1.54.5
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.0.0
  - pip=24.3.1
  - propcache=0.2.0
  - proto-plus=1.25.0
  - protobuf=5.28.2
  - pthread-stubs=0.4
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-slugify=8.0.4
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.5.1
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - responses=0.18.0
  - rich=13.9.4
  - rsa=4.9
  - s2n=1.5.9
  - safetensors=0.4.5
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.5.0
  - six=1.16.0
  - sleef=3.7
  - snappy=1.2.1
  - sniffio=1.3.1
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tbb=2021.13.0
  - text-unidecode=1.3
  - tiktoken=0.8.0
  - tk=8.6.13
  - tokenizers=0.20.3
  - tqdm=4.67.0
  - transformers=4.46.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - wheel=0.45.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.17.2
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6