benchmark_filename: CARDBench.csv

system_prompt: "You are a highly knowledgeable and experienced expert in the healthcare and biomedical field, possessing extensive medical knowledge and practical expertise."

models:
  gpt-4o:
    use: false
  gemini-1.5-pro:
    use: false
  gemma-2-2b-it:
    use: true

metrics:
  LLMEVAL:
    use: true

parallelism:
  workers: 4