benchmark_filename: CARDBioBench.csv
template_benchmark_filename: CARDBioBenchTemplate.csv
run_template: true
template_samples: 10
system_prompt: "You are a highly knowledgeable and experienced expert in the healthcare and biomedical field, possessing extensive medical knowledge and practical expertise. If you do not know the answer to a question, explicitly state that you do not know."
bioscore_system_prompt: "You are a highly knowledgeable and experienced expert in the healthcare and biomedical field, possessing extensive medical knowledge and practical expertise."
max_tokens: 1024
temperature: 0
grading_model: gpt-4o
cache_directory: ../.cache/huggingface

run_scripts:
  run_responses: true
  run_metrics: true
  run_graphs: true

models:
  gpt-4o:
    use: true
  gemini-1.5-pro:
    use: true
  claude-3.5-sonnet:
    use: true
  perplexity-sonar-huge:
    use: true
  gemma-2-27b-it:
    use: true
  llama-3.1-70b-it:
    use: true

metrics:
  BioScore:
    use: true
  BLEU_ROUGE_BERT:
    use: true