benchmark_filename: CARDBench.csv

system_prompt: "You are a highly knowledgeable and experienced expert in the healthcare and biomedical field, possessing extensive medical knowledge and practical expertise."

models:
  gpt-4o:
    use: true
  gemini-1.5-pro:
    use: true
  claude-3.5-sonnet:
    use: true
  perplexity-llama-3.1-sonar-large-128k-chat:
    use: true
  gemma-2-2b-it:
    use: false

grading_model: gpt-4o

max_new_tokens: 512

metrics:
  LLMEVAL:
    use: true

parallelism:
  workers: 1