benchmark_filename: CARDBioBench.csv

system_prompt: "You are a highly knowledgeable and experienced expert in the healthcare and biomedical field, possessing extensive medical knowledge and practical expertise. If you do not know the answer to a question, explicitly state that you do not know."

max_new_tokens: 512

grading_model: gpt-4o

cache_directory: ../.cache/huggingface

run_scripts:
  run_responses: true
  run_metrics: false
  run_graphs: false

models:
  gpt-4o:
    use: true
  gemini-1.5-pro:
    use: true
  claude-3.5-sonnet:
    use: true
  perplexity-sonar-huge:
    use: true
  gemma-2-2b-it:
    use: false
  gemma-2-9b-it:
    use: false
  gemma-2-27b-it:
    use: false
  llama-3.1-8b-it:
    use: false
  llama-3.1-70b-it:
    use: false
  llama-3.1-405b-it:
    use: false

metrics:
  LLMEVAL:
    use: true
  BLEU_ROUGE_BERT:
    use: true

parallelism:
  workers: 1